version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: orderservice-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orderservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_orders:/var/lib/postgresql/data

volumes:
  pgdata_orders: